require('dotenv').config()
const express = require('express')
const cors = require('cors')
const helmet = require('helmet')
const compression = require('compression')

const authRoutes = require('./routes/auth')
const schoolRoutes = require('./routes/schools')
const kakaoRoutes = require('./routes/kakao')
const adminRoutes = require('./routes/admin')
const schoolAdminRoutes = require('./routes/schoolAdmin')
const { paymentRouter, registrationRouter, adminRefundRouter } = require('./routes/payments')
const eventRoutes = require('./routes/events')
const whitelistRoutes = require('./routes/whitelist')
const registrationDomainRoutes = require('./routes/registrations')
const checkinRoutes = require('./routes/checkin')
const noticeRoutes = require('./routes/notices')
const notificationRoutes = require('./routes/notifications')
const inquiryRoutes = require('./routes/inquiries')
const certRequestRoutes = require('./routes/certRequests')
const delegationRoutes = require('./routes/delegation')
const bookmarkRoutes = require('./routes/bookmarks')
const eventInteractionRoutes = require('./routes/eventInteractions')
const { start: startRefundWorker } = require('./workers/refundWorker')
const { start: startReleaseWorker } = require('./workers/releaseWorker')
const { start: startRoleExpiryWorker } = require('./workers/roleExpiryWorker')

const app = express()

app.use(compression())
app.use(helmet())
app.use(cors({ origin: process.env.FRONTEND_URL, credentials: true }))
app.use(express.json())

app.use('/api/auth', authRoutes)
app.use('/api/auth/kakao', kakaoRoutes)
app.use('/api/schools', schoolRoutes)
app.use('/api/admin', adminRoutes)
app.use('/api/school-admin', schoolAdminRoutes)
app.use('/api/v1/payments', paymentRouter)
// 행사신청 도메인(사용자) — 무료 신청·취소·내 티켓
app.use('/api/v1/registrations', registrationDomainRoutes)
// 결제 도메인(다른 팀원) — 유료 본인 환불(POST /:id/cancel)
app.use('/api/v1/registrations', registrationRouter)
app.use('/api/v1/admin', adminRefundRouter)
app.use('/api/v1/events', eventRoutes)
app.use('/api/v1/events/:eventId/whitelist', whitelistRoutes)
app.use('/api/v1/checkin', checkinRoutes)
app.use('/api/notices', noticeRoutes)
app.use('/api/notifications', notificationRoutes)
app.use('/api/inquiries', inquiryRoutes)
app.use('/api/cert-requests', certRequestRoutes)
app.use('/api/delegations', delegationRoutes)
app.use('/api/bookmarks', bookmarkRoutes)
app.use('/api/v1', eventInteractionRoutes)

app.use((err, req, res, next) => {
  console.error(err)
  res.status(500).json({ message: '서버 오류가 발생했습니다.' })
})

const PORT = process.env.PORT || 4000
app.listen(PORT, () => {
  console.log(`Auth server running on port ${PORT}`)
  startRefundWorker()
  startReleaseWorker()
  startRoleExpiryWorker()
})
